import os
from enum import Enum

class EnvironmentVariables(str, Enum):
    RABBITMQ_USERNAME = 'RABBITMQ_USERNAME'
    RABBITMQ_PASSWORD = 'RABBITMQ_PASSWORD'
    RABBITMQ_HOST = 'RABBITMQ_HOST'
    RABBITMQ_EXCHANGE = 'RABBITMQ_EXCHANGE'
    SERVER_PORT = 'SERVER_PORT'
    SERVER_HOST = 'SERVER_HOST'
    INFLUXDB_NAME = 'INFLUXDB_NAME'
    DOCKER_INFLUXDB_INIT_HOST = 'DOCKER_INFLUXDB_INIT_HOST'
    DOCKER_INFLUXDB_INIT_PORT = 'DOCKER_INFLUXDB_INIT_PORT'
    DOCKER_INFLUXDB_INIT_ADMIN_TOKEN = 'DOCKER_INFLUXDB_INIT_ADMIN_TOKEN'
    DOCKER_INFLUXDB_INIT_ORG = 'DOCKER_INFLUXDB_INIT_ORG'
    DOCKER_INFLUXDB_INIT_BUCKET = 'DOCKER_INFLUXDB_INIT_BUCKET'
    MONGO_INITDB_DATABASE = 'MONGO_INITDB_DATABASE'
    MONGO_INITDB_ROOT_USERNAME = 'MONGO_INITDB_ROOT_USERNAME'
    MONGO_INITDB_ROOT_PASSWORD = 'MONGO_INITDB_ROOT_PASSWORD'

    def get_env(self, variable=None):
        return os.environ.get(self, variable)