FROM python:3.8

RUN apt-get update && apt-get install -y netcat && apt-get clean

# Make a directory for our app
WORKDIR /receiver

# Install dependencies
COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

# Copy our source code
COPY /api ./api

# Copy the wait-for-rabbitmq script
COPY receiver_entrypoint.sh .
RUN chmod +x receiver_entrypoint.sh

# Run the application
CMD ["./receiver_entrypoint.sh", "rabbitmqServer", "python", "-m", "api"]
